pluginManagement {
    repositories {
        // 本地仓库
        mavenLocal()
        // 中央仓库
        gradlePluginPortal()
        // Forge
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        // ParchmentMC
        maven {
            name = "ParchmentMC"
            url = 'https://maven.parchmentmc.org'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

rootProject.name = 'MaidsoulKitchen'

// 声明子模块（core为主模块，legacy为子模块）
include 'Main'