@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.wallev.maidsoulkitchen.handler;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;